### ISSUE TITLE
Icon for Organization & Project

### ISSUE THREAD

**Issue by mubaris** [curiositylab/curiosity#32]
Since I haved moved the repo, we need an icon for repo & organization.

Any Ideas?

CC: @alejandronanez @maiquynhtruong @raulvillares @asiyani

**Comment by alejandronanez** [comment]
This is such a complicated question for me haha!
What about a magnifying glass - when you're curious you look for something.

**Comment by mubaris** [comment]
@alejandronanez We will wait for others opinions :smile:

**Comment by maiquynhtruong** [comment]
I guess you should put an octocat in the logo if you plan to use github API more in the future. Name-wise, a magnifying glass sounds good to me. I originally thought of a question mark but a magnifying glass looks better

**Comment by mubaris** [comment]
@maiquynhtruong We need something unique. I like the octocat one. But, it just not unique. Maybe we should use Magnifying Glass over an Octocat :smile:

**Comment by alejandronanez** [comment]
Maybe you can find a good octocat here @mubaris @maiquynhtruong https://octodex.github.com/

**Comment by mubaris** [comment]
We cannot use any kind of Octocat in our application. It's clearly mentioned in the [FAQ Section](https://octodex.github.com/faq.html)

**Comment by alejandronanez** [comment]
@mubaris yeah you're right about that, what a bummer!

**Comment by raulvillares** [comment]
https://logomakr.com seems like a good online tool for easily create logos. It's free but they ask to provide credit for using the graphics. Some test I just made:

![logomakr_4dwokf](https://cloud.githubusercontent.com/assets/19681704/26717671/82900d7c-477e-11e7-94bd-16f191227874.png)

**Comment by alejandronanez** [comment]
Hey I like that one @raulvillares !

**Comment by mubaris** [comment]
@raulvillares I like that one

**Comment by raulvillares** [comment]
I'm afraid we may not be allowed to use this logo because there's a octocat behind the hat and glasses. What do you think?

![image](https://cloud.githubusercontent.com/assets/19681704/26781417/a673f808-49ee-11e7-9db2-07883769cae5.png)

Maybe I can work on something related to a spy octopus? (though graphic design it's not really my thing...):

![image](https://cloud.githubusercontent.com/assets/19681704/26781223/ad51fb58-49ed-11e7-82b6-2f4b5f1b00b6.png)

**Comment by alejandronanez** [comment]
Your skills are better than mine for sure haha. I like the octopus.

**Comment by maiquynhtruong** [comment]
I still want the octocat. But I think we can use something with a search icon (magnifying glass) to show the nature of searching for github repos 😃

**Comment by raulvillares** [comment]
@maiquynhtruong I'm afraid [we can't use the octocat](https://octodex.github.com/faq.html).

I got some more ideas. Maybe we can choose a not so bad icon for now, just to get rid of the ugly default one.

[Option 1](https://logomakr.com/1sPrc0)

![image](https://user-images.githubusercontent.com/19681704/26869438-c3648d0e-4b6c-11e7-96dc-00d1fa37841e.png)

[Option 2](https://logomakr.com/5OZJ7B)

![image](https://user-images.githubusercontent.com/19681704/26869367-7f253c1a-4b6c-11e7-8c69-8145198e3b17.png)

[Option 3](https://logomakr.com/3Rl18u)

![image](https://user-images.githubusercontent.com/19681704/26869523-049b8e4e-4b6d-11e7-8b2b-95ab0575ad9a.png)

[Option 4](https://logomakr.com/4Xprgt)

![image](https://user-images.githubusercontent.com/19681704/26869556-1e6384f8-4b6d-11e7-91ce-e5a68216a732.png)

[Option 5](https://logomakr.com/4FnAFr)

![image](https://user-images.githubusercontent.com/19681704/26869596-40e1f988-4b6d-11e7-8d76-dc38dc0bc9a1.png)

[Option 6](https://logomakr.com/4FnAFr)

![image](https://user-images.githubusercontent.com/19681704/26869642-66ab1438-4b6d-11e7-97b8-5a4d0c603d9c.png)

**Comment by mubaris** [comment]
I like the option 3

**Comment by alejandronanez** [comment]
I like option 3 too. Awesome work @raulvillares

**Comment by raulvillares** [comment]
We got a winner.

I've just change the icon. It's problaby a good idea to keep somewhere the file and the [link to modify it](https://logomakr.com/8ShF2G).

![image](https://user-images.githubusercontent.com/19681704/26884883-2d4d373c-4ba1-11e7-8148-2a52a0e313d2.png)

**Comment by alejandronanez** [comment]
Thanks for the initiative Raúl, this is what makes open source great!

**Comment by maiquynhtruong** [comment]
@raulvillares I understand Github doen't allow the use of octocat. I was just saying the perfect logo would include an octocat but since we can't have it, we need to use something else.

Option 3 looks good to me too. Thanks for the great work :smile:

**Comment by maiquynhtruong** [comment]
I think we should close this one because we have a lot of issues right now.

**Comment by mubaris** [comment]
Yeah, we should close this.

Thanks @raulvillares for your awesome work.
