### ISSUE TITLE
Create a Github project for the sake of organization and goals

### ISSUE THREAD

**Issue by alejandronanez** [curiositylab/curiosity#34]
It will help us to create a project and start a new branch for it, the key parts I think should be there are:

- Move to webpack/rollup
- Choose a JS framework
- Write some critical unit tests

Once we have that we can start building new awesome things 💯

**Comment by mubaris** [comment]
@alejandronanez I promoted you as an Owner of this organization. I don't have any experience with Github Projects. Maybe you could help with that.

**Comment by alejandronanez** [comment]
@mubaris sweet.

**Comment by alejandronanez** [comment]
The project already exists. https://github.com/curiositylab/curiosity/projects/1

Closing this.
