### ISSUE TITLE
Update Readme with instructions

### ISSUE THREAD

**Issue by alejandronanez** [curiositylab/curiosity#37]
Instructions about contributing, branching, etc.

**Comment by maiquynhtruong** [comment]
Or just update README in general. I think the picture should be updated.

**Comment by mubaris** [comment]
Welcome to `Curiosity`. Be sure to take it. Always good to see new
contributors. If you have any doubts, let us know.

**Comment by alejandronanez** [comment]
@elia314 go for it! Welcome

**Comment by elia314** [comment]
I updated it on this fork and created a pull request. However, I cannot add reviewers, not sure how to do that. Any thoughts?

https://github.com/curiositylab/curiosity/pull/53

**Comment by mubaris** [comment]
I've closed #53 

Points to be noted.

* This is a web app. This is not a chrome extension. Chrome extension is based on logic of this app. That's completely different thing. You don't need to edit the `Get Chrome Extension` part.
* Do not move badges to another section.
* Rename `Tools I used` to `Dependencies`. This section is the list of libraries/frameworks/tools which are dependencies of `Curiosity` app.
* We have 3 branches. `gh-pages` contains only front-end and it's hosted on Github Pages. `v2` is the future of Curiosity. We are building a backend for this. The code for that is contained in `v2`. `master` is main branch. `v2` will be merged to `master` once the process of building backend is done.
* You need to change the screenshot of Curiosity in the `Peek at Curiosity` section. Upload the image to [imgsafe](http://imgsafe.org) then set the link.
* We use Github labels and Github projects to manage tasks. `up-for-grabs` labels are the issues need to solved. `discussion` is for discussions. Check all labels and write about it. It's pretty straight forward.

**Send it in one Commit.**

Anything else @alejandronanez

**Comment by alejandronanez** [comment]
Hmmm...I think you covered everything here.

You can still send multiple commits @elia314 when we merge your PR we will sqash everything into one commit, so that's fine. Let me configure that @mubaris

**Comment by alejandronanez** [comment]
@mubaris do you think we can re-open #53 and just request changes to @elia314?
Now the only way to merge is by using the `Squash and merge` button.

**Comment by mubaris** [comment]
Cool

**Comment by elia314** [comment]
I updated it in pull request #55, I didn't know what image you wanted for
"Peek at Curiosity" though. I also didn't know how to merge updates into
old pull requests #53.

I'm still very new to this, please provide any feedback and I'd be happy to
continue updating. Thanks again.

**Comment by maiquynhtruong** [comment]
@elia314 I think an updated image of the current version of this project is good enough. Something like this http://i.imgsafe.org/c45b215899.jpg
