### ISSUE TITLE
Add All Contributors to the repo!

### ISSUE THREAD

**Issue by alejandronanez** [curiositylab/curiosity#38]
Let's show some love to the people that have contributed in any way to this repo!

We should follow this, https://github.com/kentcdodds/all-contributors

I think this is a good PR for someone looking for his/her first contribution to OSS 🥇

**Comment by mubaris** [comment]
I think this is a good idea. Yeah, we should leave it for someone to do their first contribution.

**Comment by vvvdeep** [comment]
@mubaris @alejandronanez , created a PR for this #46 . Let me know what you think.
