### ISSUE TITLE
Add Preference button

### ISSUE THREAD

**Issue by mubaris** [curiositylab/curiosity#39]
We need to add a preference button on the right side. It will be used for managing usernames.

- [x] Remove username management from the main page
- [x] Add a preference button on the right side. Preferably `font-awesome`
- [x] Move username management to preference

**Comment by vvvdeep** [comment]
Hey @mubaris , I can work on this if no one started yet.

**Comment by mubaris** [comment]
@vvvdeep We appreciate your contributions. But @maiquynhtruong is already working on it. But you can work on #38. It's very easy to do it. Be sure to contact us on Gitter if you have any problems. We always welcome new contributors. Thank you.

**Comment by vvvdeep** [comment]
Thanks @mubaris .
I am starting on #38
