### ISSUE TITLE
Settings button isn't working on chrome

### ISSUE THREAD

**Issue by mubaris** [curiositylab/curiosity#47]
The settings button was introduced in #41 

It's not working on Chrome in our fork. But the [original fork](maiquynhtruong.github.io/curiosity) is working. We have to fix ASAP.

Maybe @vvvdeep or @maiquynhtruong can work on this

**Comment by maiquynhtruong** [comment]
Sure I'll take a look

**Comment by mubaris** [comment]
@maiquynhtruong What is the progress on this?

**Comment by maiquynhtruong** [comment]
I just looked at that now and it seems like an easy fix. So I'll make a PR shortly.

**Comment by maiquynhtruong** [comment]
Is this still an issue? Should we close it? @mubaris

**Comment by mubaris** [comment]
We should close it. Next time you send PR for issues, write `closes #issueNumber` or `fixes #issueNumber` in the description.

[Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)
