### ISSUE TITLE
Allow users to add and remove usernames

### ISSUE THREAD

**Issue by haganbmj** [curiositylab/curiosity#6]
Allow users to add watched usernames.
- Persist this list to localStorage.

**Comment by mubaris** [comment]
Good suggestion. Thanks!!

I'll implement this.

:+1:

**Comment by mubaris** [comment]
@maiquynhtruong Implemented part of this issue in #16 , but we need to make it permanent by adding it to `localStorage`. Till that point, this issue will be open.

**Comment by maiquynhtruong** [comment]
is there anyway we can change usernames.js using javascript?

**Comment by mubaris** [comment]
In client side JS we can't change files. ie We don't have permission to do **File I/O**. But what we can do is we can store the username array in `localStorage`. Then we can add/remove/modify the username array.

* [HTMLDog Local Storage](http://htmldog.com/guides/javascript/advanced/localstorage/)
* [Mozilla Developer Network Local Storge Tutorial](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage)
* [9 JS Local Storage Libraries](https://www.sitepoint.com/9-javascript-libraries-working-with-local-storage/)
* [Store.js](https://github.com/marcuswestin/store.js/)
* [store](https://github.com/nbubna/store)

Above link are useful if you are not familiar with `localStorage` or you can use above libraries.

**Comment by maiquynhtruong** [comment]
I did not know about `localStorage` before. Looking the links you had I can I think I can implement that. I think at first all the usernames from usernames.js will be stored in local storage and the program will use that local storage from there.

**Comment by mubaris** [comment]
Yep. That's what we want.

**Comment by mubaris** [comment]
@maiquynhtruong Instead of showing all usernames in the main page, we should move it to something like preferences.

We should add a preference icon on the right/left side. Then When user clicks it, We show the `swal` to add/remove/modify current usernames.

@maiquynhtruong If you are working on this keep this in mind.
